SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[sp_SaveInstructionChange]
(@InstructionChangeId  INT            = NULL, 
 @CancellationReason   VARCHAR(200)   = NULL, 
 @StatusId             INT, 
 @InstructionPaymentId INT            = NULL, 
 @ProviderId           INT, 
 @ClientName           VARCHAR(50), 
 @Telephone            VARCHAR(10)    = NULL, 
 @Email                VARCHAR(50)    = NULL, 
 @ValidationCode       VARCHAR(5)     = NULL, 
 @TransactionNumber    VARCHAR(50), 
 @NewPayer             VARCHAR(30)    = NULL, 
 @Account              VARCHAR(20)    = NULL, 
 @NewRecipient         VARCHAR(50)    = NULL, 
 @RecipientName        VARCHAR(50)    = NULL, 
 @NewKey               VARCHAR(20)    = NULL, 
 @CreationDate         DATETIME, 
 @CreatedBy            INT, 
 @AgencyId             INT, 
 @ChangeTypeId         INT, 
 @IsSent               BIT, 
 @Usd                  DECIMAL(18, 2)  = NULL, 
 @City                 VARCHAR(50)    = NULL, 
 @AccountIsCheck       BIT            = NULL, 
 @Request              VARCHAR(3)     = NULL, 
 @ChooseMsg            BIT            = NULL, 
 @Note                 VARCHAR(400)   = NULL, 
 @LastUpdatedOn        DATETIME       = NULL, 
 @LastUpdatedBy        INT            = NULL, 
 @IdSaved              INT OUTPUT, 
 @IsReenter            BIT            = NULL, 
 @OperationType        BIT            = NULL, 
 @ValidatedBy          INT            = NULL, 
 @ValidatedOn          DATETIME       = NULL, 
 @ChangeReasonId       INT            = NULL,
 @NewTransactionNumber    VARCHAR(50) = null ,
  @NewProviderId           INT = null
)
AS
    BEGIN
        IF(@InstructionChangeId IS NULL)
            BEGIN
                INSERT INTO [dbo].[InstructionChange]
                (CreationDate, 
                 ClientName, 
                 TransactionNumber, 
                 StatusId, 
                 ChangeTypeId, 
                 ProviderId, 
                 Telephone, 
                 ValidationCode, 
                 CreatedBy, 
                 AgencyId, 
                 InstructionPaymentId, 
                 NewPayer, 
                 Account, 
                 NewRecipient, 
                 CancellationReason, 
                 IsSent, 
                 RecipientName, 
                 NewKey, 
                 Usd, 
                 CityName, 
                 AccountIsCheck, 
                 Request, 
                 LastUpdatedBy, 
                 LastUpdatedOn, 
                 ChooseMsg, 
                 IsReenter, 
                 OperationType, 
                 ValidatedBy, 
                 ValidatedOn, 
                 Email,
				 ChangeReasonId,
				 NewTransactionNumber,
				 NewProviderId
                )
                VALUES
                (@CreationDate, 
                 @ClientName, 
                 @TransactionNumber, 
                 @StatusId, 
                 @ChangeTypeId, 
                 @ProviderId, 
                 @Telephone, 
                 @ValidationCode, 
                 @CreatedBy, 
                 @AgencyId, 
                 @InstructionPaymentId, 
                 @NewPayer, 
                 @Account, 
                 @NewRecipient, 
                 @CancellationReason, 
                 @IsSent, 
                 @RecipientName, 
                 @NewKey, 
                 @Usd, 
                 @City, 
                 @AccountIsCheck, 
                 @Request, 
                 @LastUpdatedBy, 
                 @LastUpdatedOn, 
                 @ChooseMsg, 
                 @IsReenter, 
                 @OperationType, 
                 @ValidatedBy, 
                 @ValidatedOn, 
                 @Email,
				 @ChangeReasonId,
				 @NewTransactionNumber,
				  @NewProviderId
                );
                SET @IdSaved = @@IDENTITY;
            END;
            ELSE
            BEGIN
                UPDATE [dbo].[InstructionChange]
                  SET 
                --CreationDate = @CreationDate, 
                      ClientName = @ClientName, 
                      TransactionNumber = @TransactionNumber, 
                      StatusId = @StatusId, 
                      ChangeTypeId = @ChangeTypeId, 
                      ProviderId = @ProviderId, 
                      Telephone = @Telephone, 
                      ValidationCode = @ValidationCode, 
                      --CreatedBy = @CreatedBy, 
                      AgencyId = @AgencyId, 
                      InstructionPaymentId = @InstructionPaymentId, 
                      NewPayer = @NewPayer, 
                      Account = @Account, 
                      NewRecipient = @NewRecipient, 
                      CancellationReason = @CancellationReason, 
                      IsSent = @IsSent, 
                      RecipientName = @RecipientName, 
                      NewKey = @NewKey, 
                      Usd = @Usd, 
                      CityName = @City, 
                      Request = @Request, 
                      ChooseMsg = @ChooseMsg, 
                      Note = @Note, 
                      LastUpdatedBy = @LastUpdatedBy, 
                      LastUpdatedOn = @LastUpdatedOn,
					  ChangeReasonId = @ChangeReasonId,
					  NewTransactionNumber = @NewTransactionNumber,
					   NewProviderId = @NewProviderId ,
					        AccountIsCheck = @AccountIsCheck 
                WHERE InstructionChangeId = @InstructionChangeId;
                SET @IdSaved = @InstructionChangeId;
            END;
    END;
GO