CREATE TABLE [dbo].[CashierApplyComissions] (
  [ComissionApplyId] [int] IDENTITY,
  [CashierId] [int] NOT NULL,
  [ApplyCitySticker] [bit] NULL,
  [StartDateCitySticker] [date] NULL,
  [CreationDateCitySticker] [datetime] NULL,
  [ApplyPlateSticker] [bit] NULL,
  [CreatedByCitySticker] [int] NULL,
  [CreationDatePlateSticker] [datetime] NULL,
  [StartDatePlateSticker] [date] NULL,
  [CreatedByPlateSticker] [int] NULL,
  [ApplyParkingTicket] [bit] NULL,
  [ApplyParkingTicketCard] [bit] NULL,
  [ApplyTitlesAndPlates] [bit] NULL,
  [CreationDateTitlesAndPlates] [datetime] NULL,
  [StartDateTitlesAndPlates] [date] NULL,
  [ApplyTitlesAndPlatesManual] [bit] NULL,
  [CreatedByTitlesAndPlates] [int] NULL,
  [ApplyTrp730] [bit] NULL,
  [CreationDateTrp730] [datetime] NULL,
  [StartDateTrp] [date] NULL,
  [CreatedByTrp] [int] NULL,
  [ApplyFinancing] [bit] NULL,
  [ApplyTelephones] [bit] NULL,
  [CreationDateTelephones] [datetime] NULL,
  [StartDateTelephones] [date] NULL,
  [CreatedByTelephones] [int] NULL,
  [ApplyNotary] [bit] NULL,
  [ApplyLendify] [bit] NULL,
  [CreationDateLendify] [datetime] NULL,
  [StartDateLendify] [date] NULL,
  [CreatedByLendify] [int] NULL,
  [ApplyTickets] [bit] NULL,
  [CreationDateTickets] [datetime] NULL,
  [StartDateTickets] [datetime] NULL,
  [CreatedByTickets] [int] NULL,
  [ApplyNewPolicy] [bit] NULL,
  [CreationDateNewPolicy] [datetime] NULL,
  [StartDateNewPolicy] [datetime] NULL,
  [CreatedByNewPolicy] [int] NULL,
  [ApplyMonthlyPayment] [bit] NULL,
  [CreationDateMonthlyPayment] [datetime] NULL,
  [StartDateMonthlyPayment] [datetime] NULL,
  [CreatedByMonthlyPayment] [int] NULL,
  [ApplyRegistrationRelease] [bit] NULL,
  [CreationDateRegistrationRelease] [datetime] NULL,
  [StartDateRegistrationRelease] [datetime] NULL,
  [CreatedByRegistrationRelease] [int] NULL,
  [ApplyEndorsement] [bit] NULL,
  [CreationDateEndorsement] [datetime] NULL,
  [StartDateEndorsement] [datetime] NULL,
  [CreatedByEndorsement] [int] NULL,
  [ApplyPolicyRenewal] [bit] NULL,
  [CreationDatePolicyRenewal] [datetime] NULL,
  [StartDatePolicyRenewal] [datetime] NULL,
  [CreatedByPolicyRenewal] [int] NULL,
  CONSTRAINT [PK_CashierApplyComissions] PRIMARY KEY CLUSTERED ([ComissionApplyId])
)
ON [PRIMARY]
GO