CREATE TABLE [dbo].[InstructionChange] (
  [InstructionChangeId] [int] IDENTITY,
  [CreationDate] [datetime] NOT NULL,
  [ClientName] [varchar](50) NOT NULL,
  [TransactionNumber] [varchar](50) NOT NULL,
  [StatusId] [int] NOT NULL,
  [ChangeTypeId] [int] NOT NULL,
  [ProviderId] [int] NOT NULL,
  [Telephone] [varchar](10) NULL,
  [ValidationCode] [varchar](5) NULL,
  [CreatedBy] [int] NOT NULL,
  [AgencyId] [int] NOT NULL,
  [InstructionPaymentId] [int] NULL,
  [NewPayer] [varchar](30) NULL,
  [Account] [varchar](20) NULL,
  [NewRecipient] [varchar](50) NULL,
  [CancellationReason] [varchar](200) NULL,
  [IsSent] [bit] NOT NULL CONSTRAINT [DF_InstructionChange_IsSent] DEFAULT (0),
  [RecipientName] [varchar](50) NULL,
  [NewKey] [varchar](20) NULL,
  [Usd] [decimal](18, 2) NULL,
  [CityName] [varchar](50) NULL,
  [AccountIsCheck] [bit] NULL,
  [Request] [varchar](3) NULL,
  [Note] [varchar](400) NULL,
  [LastUpdatedBy] [int] NULL,
  [LastUpdatedOn] [datetime] NULL,
  [ChooseMsg] [bit] NULL CONSTRAINT [DF_InstructionChange_ChooseMsg] DEFAULT (0),
  [IsReenter] [bit] NULL,
  [OperationType] [bit] NULL CONSTRAINT [DF_InstructionChange_ChooseMsg1] DEFAULT (0),
  [ValidatedBy] [int] NULL,
  [ValidatedOn] [datetime] NULL,
  [Email] [varchar](50) NULL,
  [ChangeReasonId] [int] NULL,
  [NewTransactionNumber] [varchar](50) NULL,
  [NewProviderId] [int] NULL,
  CONSTRAINT [PK_IntructionChange] PRIMARY KEY CLUSTERED ([InstructionChangeId])
)
ON [PRIMARY]
GO